# fly.toml app configuration file generated for autumn-grass-7257 on 2023-09-17T22:09:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-grass-7257"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
